/*
 * Automatically generated by configure - do not modify
 * Configured with: * '/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/thirdparty/liburing/configure' * '--prefix=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install' * '--libdir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/lib' * '--includedir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/include'
 */
#define CONFIG_NOLIBC
#define CONFIG_HAVE_KERNEL_RWF_T
#define CONFIG_HAVE_KERNEL_TIMESPEC
#define CONFIG_HAVE_OPEN_HOW
#define CONFIG_HAVE_STATX
#define CONFIG_HAVE_GLIBC_STATX
#define CONFIG_HAVE_CXX
#define CONFIG_HAVE_UCONTEXT
#define CONFIG_HAVE_STRINGOP_OVERFLOW
#define CONFIG_HAVE_ARRAY_BOUNDS
#define CONFIG_HAVE_NVME_URING
#define CONFIG_HAVE_FANOTIFY
#define CONFIG_HAVE_FUTEXV
#define CONFIG_HAVE_UBLK_HEADER
