# Automatically generated by configure - do not modify
# Configured with: '/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/thirdparty/liburing/configure' '--prefix=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install' '--libdir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/lib' '--includedir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/include'
prefix=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install
includedir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/include
libdir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/lib
libdevdir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/lib
relativelibdir=
mandir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/man
datadir=/mnt/c/Users/Lily/Desktop/Homework/程序设计大作业/bpt-implement/cmake-build-debug/liburing_install/share
libgcc_link_flag=/usr/lib/gcc/x86_64-linux-gnu/13/libgcc.a
CONFIG_NOLIBC=y
CONFIG_HAVE_KERNEL_RWF_T=y
CONFIG_HAVE_KERNEL_TIMESPEC=y
CONFIG_HAVE_OPEN_HOW=y
CONFIG_HAVE_STATX=y
CONFIG_HAVE_GLIBC_STATX=y
CONFIG_HAVE_CXX=y
CONFIG_HAVE_UCONTEXT=y
CONFIG_HAVE_STRINGOP_OVERFLOW=y
CONFIG_HAVE_ARRAY_BOUNDS=y
CONFIG_HAVE_NVME_URING=y
CONFIG_HAVE_FANOTIFY=y
CONFIG_HAVE_FUTEXV=y
CONFIG_HAVE_UBLK_HEADER=y
CC=gcc
CXX=g++
